language: java
install:
- mvn -Pstandalone-app -DskipTests=true -Dmaven.javadoc.skip=true -B -V install
jdk:
- oraclejdk8
deploy:
  provider: releases
  api_key:
    secure: KU+vkEvX1JW649czaptgftAqO1mNVXHHKpNG8qzYtOBdLAJd3j3I4DeAJJDe6RH2MeaYcxuNa0ygBQV3+o+C4bGwgDmgdUjMVk+QWXgKdRuK7C+bxhfNtN/5e2gSsyMNFayCGdre3laPiqypqZLnjuKymYAZIt1hyc/x24Nue/yTrrg6tBcGqpB8slMSbMh8Vohg1j27PXetKGnMZpXOj6AIMAh6ctrqmCUBhDzwo2unR2GyNpDTJOp/ry6pHwAYJAxhUq7BuNsFPWXSEYdEdqFbTq9ZknEjnDoWxTTodif5GYfJfs1wzU5mTLtc93zRSjgbQMv37b9Y1fI+4QboeB7Qs8V64Fvxgclx89N3m0IqaDScBfZYdET//BAkPLknt83bWogbcwyBU1Ab16vM5m/sG1y5qBpQrXmbq9VfqU9+e2HZK1IpB53+0XFWbcZcPC/yVZ+nsULyLtQvsmR+HU4AH3oKgjNcYx9yaLRNysi5GcIWnxteBGbNRuSgiNG0u4RRjX3oZf7oJCbH3Or0qtcufJB1h4eUj6P2ul1D2odSDLoCgoGxEUCwfDn2ZiH4zF7Zw0MOOHRKkRu+c5mYcVkKLIt9sY/SJEAEnlu67RrK8VepCLAPdM4ZQVSvc8Zuot+Vn468x5DcOcpUL6oCibyHbTvuL7yPCX4yxo9aAxc=
  file_glob: true
  file: simplegen/target/simplegen-*.jar
  on:
    repo: derkork/simplegen
    tags: true
